name: CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
          path: |
            ~/.cache/go-build
            ${{ env.GOMODCACHE }}

      - name: Prepare GOMODCACHE env
        run: echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Install deps (module download)
        run: go mod download

      - name: Run unit tests
        run: go test ./... -v

