name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # compute GOMODCACHE/GOCACHE envs before caching
      - name: Prepare GOMODCACHE and GOCACHE env
        run: |
          echo "GOMODCACHE=$(go env GOMODCACHE)" >> $GITHUB_ENV
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

      - name: Cache Go modules and build cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('src/**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
          path: |
            ${{ env.GOMODCACHE }}
            ${{ env.GOCACHE }}
            ~/.cache/go-build

      - name: Install deps (module download)
        run: go mod download
        working-directory: src

      - name: Run unit tests
        run: go test ./... -v
        working-directory: src

